// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrmqxbmkmrlkrevlsmpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpybXF4Ym1rbXJsa3JldmxzbXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzgxMDksImV4cCI6MjA3MTcxNDEwOX0.UcsZW2ndAxt3_uzOnCs5rTMlX0P7e5jVHy9tIgqfKCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});